# 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
import numpy as np

row = np.matrix([0,1]*4)
column =np.matrix([0,1]*4).T
mat1 = column*row

row = np.matrix([1,0]*4)
column =np.matrix([1,0]*4).T
mat2 = column*row

mat = mat1+mat2
print(mat)
print("------------")
mat = np.ones((8,8))
mat[0:8:2,0:8:2]=0
mat[1:8:2,1:8:2]=0
print(mat)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
------------
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4 Для создания
необходимо использовать функцию arrange.

In [296]:
mat = np.arange(25).reshape(5,5)%5
print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [118]:
mat = np.random.random((3,3,3))
print(mat)

[[[0.44182897 0.81666717 0.84726072]
  [0.78506196 0.49595511 0.57617779]
  [0.41580665 0.25582227 0.96106872]]

 [[0.33051866 0.54749558 0.44118784]
  [0.87470386 0.36932047 0.59653435]
  [0.30135847 0.5013711  0.95686004]]

 [[0.80753615 0.84818826 0.57200128]
  [0.24382463 0.28626662 0.31348966]
  [0.02091158 0.57255533 0.08902585]]]


# 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
n = 6
m = 9
mat = np.ones((n,m))
mat[(0+1):(n-1),(0+1):(m-1)]=0
print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [310]:
n = 9
mat = np.random.random(9)
mat.sort()
mat = np.flip(mat)
print(mat)

[0.98593043 0.62606653 0.56393754 0.53760028 0.45945585 0.4469702
 0.19541746 0.07925984 0.07808656]


# 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [314]:
x=4
y = 6
z = 1
mat = np.matrix(np.random.random((x,y,z)))
print(mat)
print("Форма матрицы =", mat.shape)
print("Размер матрицы =", mat.size)
print("Размерность матрицы =", mat.ndim)

[[0.89652001 0.29734843 0.65533628 0.37073075 0.20251645 0.11554715]
 [0.62998108 0.78728641 0.22627619 0.80248027 0.87174266 0.51673162]
 [0.16981051 0.57703268 0.0783169  0.72696637 0.49768674 0.13966167]
 [0.18080223 0.23365073 0.03782135 0.34432719 0.29031337 0.23132022]]
Форма матрицы = (4, 6)
Размер матрицы = 24
Размерность матрицы = 2


# 2.3.1 Задание
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [315]:
import pandas as pd

def euclid(a,b):
    return sum([(a[i]-b[i])**2 for i in range(0,len(a))])**(1/2)

a = pd.Series([3,1,7])
b = pd.Series([9,0,4])

print(euclid(a,b))
print(np.linalg.norm(a-b))

6.782329983125268
6.782329983125268


# 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

In [240]:
print("Недоброкачественные лекарства")
url="https://hubofdata.ru/dataset/a5e47bbf-59e6-497e-973f-fd89380f1101/resource/e53389af-df51-4dc7-8d84-b2ce1fe0e455/download/data-20190616-structure-20171120-1.csv"
print(url)
drugs = pd.read_csv(url,delimiter=";",encoding="cp1251")

Недоброкачественные лекарства
https://hubofdata.ru/dataset/a5e47bbf-59e6-497e-973f-fd89380f1101/resource/e53389af-df51-4dc7-8d84-b2ce1fe0e455/download/data-20190616-structure-20171120-1.csv


# 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [241]:
drugs.head(2)

trade_name          no_ru  \
0  МЕЛОКСИКАМ-ПРАНА, таблетки 15 мг 10 шт., упако...  ЛСР-000843/10   
1  Хлоргексидин, раствор для местного и наружного...      ЛП-003232   

        dt_ru  series                                           producer  \
0  09.02.2010  140917  Общество с ограниченной ответственностью "ПРАН...   
1  29.09.2015  090818  Общество с ограниченной ответственностью "ЮжФа...   

  country                  status                        type letter_number  \
0  Россия  недоброкачественное ЛС                       Отзыв   02И-1450/19   
1  Россия  недоброкачественное ЛС  Приостановление реализации   02И-1462/19   

  letter_date  
0  11.06.2019  
1  11.06.2019

In [235]:
drugs.tail(3)

trade_name              no_ru  \
30778  Амиксина таблетки 0.125 г, таблетки покрытые о...           96/252/3   
30779  Валокордин, капли для приема внутрь ~  шт., фл...  П N012893/01-2001   
30780  Церукал, раствор для внутривенного и внутримыш...  П N012812/02-2001   

            dt_ru  series                        producer   country  \
30778  18.06.1996   10201    Лэнс-Фарм ООО [пос.Горки-10]    Россия   
30779  10.04.2001  403031         Кревель Мойзельбах ГмбХ  Германия   
30780  21.03.2001  3D816B  Арцнаймиттельверк Дрезден ГмбХ  Германия   

                status           type letter_number letter_date  
30778  сомнительное ЛС  Фальсификация     01И-12/05  19.01.2005  
30779  сомнительное ЛС  Фальсификация      01И-8/05  17.01.2005  
30780  сомнительное ЛС  Фальсификация      01И-9/05  17.01.2005

In [236]:
drugs.shape

(30781, 10)

In [237]:
drugs.describe

<bound method NDFrame.describe of                                               trade_name              no_ru  \
0      МЕЛОКСИКАМ-ПРАНА, таблетки 15 мг 10 шт., упако...      ЛСР-000843/10   
1      Хлоргексидин, раствор для местного и наружного...          ЛП-003232   
2      Парацетамол-УБФ, таблетки 500 мг 10 шт., упако...       Р N002526/01   
3      Аммиак, раствор для наружного применения и инг...      ЛСР-005107/10   
4      Раствор анальгина, Раствор, 2 % 100 мл, бутылк...                NaN   
...                                                  ...                ...   
30776                   Пиралгин, таблетки ~  шт.,  (),   П N012815/01-2001   
30777  Левомицетина таблетки, таблетки 500 мг  шт.,  ...          70/730/56   
30778  Амиксина таблетки 0.125 г, таблетки покрытые о...           96/252/3   
30779  Валокордин, капли для приема внутрь ~  шт., фл...  П N012893/01-2001   
30780  Церукал, раствор для внутривенного и внутримыш...  П N012812/02-2001   

            dt_ru

In [238]:
drugs.iloc[1:4]

trade_name          no_ru  \
1  Хлоргексидин, раствор для местного и наружного...      ЛП-003232   
2  Парацетамол-УБФ, таблетки 500 мг 10 шт., упако...   Р N002526/01   
3  Аммиак, раствор для наружного применения и инг...  ЛСР-005107/10   

        dt_ru  series                                           producer  \
1  29.09.2015  090818  Общество с ограниченной ответственностью "ЮжФа...   
2  22.07.2008  670917  Открытое акционерное общество "Уралбиофарм" (О...   
3  01.06.2010  010518                                    ООО "Гиппократ"   

  country                  status                        type letter_number  \
1  Россия  недоброкачественное ЛС  Приостановление реализации   02И-1462/19   
2  Россия  недоброкачественное ЛС       Прекращение обращения   02И-1464/19   
3  Россия  недоброкачественное ЛС                       Отзыв   02И-1438/19   

  letter_date  
1  11.06.2019  
2  11.06.2019  
3  10.06.2019

In [239]:
drugs[drugs['country'] == 'Германия'].head(2)

trade_name          no_ru  \
147  Прадакса®, капсулы 110 мг 10 шт., блистеры (6)...  ЛСР-007065/09   
162  Простамол® Уно, капсулы 320 мг 15 шт., блистер...   П N012255/01   

          dt_ru   series                                producer   country  \
147  07.09.2009   704037  Берингер Ингельхайм Фарма ГмбХ и Ко.КГ  Германия   
162  29.12.2010  0010118          Каталент Германия Эбербах ГмбХ  Германия   

                     status                             type letter_number  \
147  недоброкачественное ЛС                            Отзыв   01И-1274/19   
162  недоброкачественное ЛС  О разрешении к реализации серии   02И-1196/19   

    letter_date  
147  20.05.2019  
162  14.05.2019

# 3.3.2 Задание
Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [316]:
from sklearn import preprocessing
url="https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
iris = pd.read_csv(url)


scale = preprocessing.MinMaxScaler(feature_range=(0,1))
sepal_minmaxed = scale.fit_transform(iris.sepal_length_cm.values.reshape(-1, 1) )
print(sepal_minmaxed.T)

[[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
  0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
  0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
  0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
  0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
  0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
  0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
  0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
  0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
  0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
  0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
  0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
  0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
  0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
  0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33

In [317]:
from scipy import stats

sepal_zscored = stats.zscore(iris.sepal_width_cm.values.reshape(-1, 1) )
print(sepal_zscored.T)

[[ 1.03205722 -0.1249576   0.33784833  0.10644536  1.26346019  1.95766909
   0.80065426  0.80065426 -0.35636057  0.10644536  1.49486315  0.80065426
  -0.1249576  -0.1249576   2.18907205  3.11468391  1.95766909  1.03205722
   1.72626612  1.72626612  0.80065426  1.49486315  1.26346019  0.56925129
   0.80065426 -0.1249576   0.80065426  1.03205722  0.80065426  0.33784833
   0.10644536  0.80065426  2.42047502  2.65187798  0.10644536  0.33784833
   1.03205722  0.10644536 -0.1249576   0.80065426  1.03205722 -1.74477836
   0.33784833  1.03205722  1.72626612 -0.1249576   1.72626612  0.33784833
   1.49486315  0.56925129  0.33784833  0.33784833  0.10644536 -1.74477836
  -0.58776353 -0.58776353  0.56925129 -1.51337539 -0.35636057 -0.8191665
  -2.43898725 -0.1249576  -1.97618132 -0.35636057 -0.35636057  0.10644536
  -0.1249576  -0.8191665  -1.97618132 -1.28197243  0.33784833 -0.58776353
  -1.28197243 -0.58776353 -0.35636057 -0.1249576  -0.58776353 -0.1249576
  -0.35636057 -1.05056946 -1.51337539 -1